### PR TITLE
Add variable heights for options

### LINKED ISSUE #31: Component Breaks With Long, Variable Height Values
I get the sense this may be a semi-known issue, but I'm filing this as a ticket just in case.

Basically: if you have a list of options which are of variable length, some of which are long enough to wrap onto a new line and some of which are not, the longer options overflow their boundaries and overlap the ones below them. This only happens when there are a large number of options, as a smaller amount of options does not cause this issue and automatically displays the heights appropriately.

I can sort of get around this by using a larger fixed height, but that means that there is a lot of whitespace for any shorter options. I don't know much about the underlying library here... is there potentially a way to keep the dynamic, automatic height calculation of the original implementation instead? I know that the height is used to calculate the size of the window, but if a fixed window height were provided instead, would 'on the fly' sizing for the displayed options then be doable? Or is this just a limitation of the windowing used to make longer lists performant?

Replication here: https://codesandbox.io/s/react-windowed-select-95ybc

(Also, as a side note, I've found that if I use a height format other than a pure number, such as "100px", it breaks so hard I have to force kill my Chrome tab. Easy enough to fix, but it might be worth noting in the documentation that heights must be provided in only that format.)

### PR DESCRIPTION
**Pull request by jchamb**
fixes #31 by adding measuring to option items. 

Note this could probably be made more efficient with measurement done through portals.

### CODE REVIEW

**Comment by amber-cd** [comment]
Hrm... we forked the PR from this branch and published it to our local NPM server in order to verify if this fix worked for our use case, but I'm still seeing the issue with overlapping option heights. @jchamb First, thank you for all the work on this so far, and second, is there something I need to add/use in the props in order to use this work?

**Comment by jacobworrel** [comment]
@amber-cd There are examples in Storybook that work. Were you able to see those working examples in the fork?

**Comment by jacobworrel** [comment]
see https://github.com/jacobworrel/react-windowed-select/pull/38

**Comment by jacobworrel** [comment]
@amber-cd just published 2.0.3 to npm with this fix. you can see a working example here: https://peaceful-leavitt-38971b.netlify.app/?path=/story/select--long-label-text
no need to do anything on your end to get this working.

**Comment by amber-cd** [comment]
Fantastic, thank you!

**Comment by jchamb** [comment]
Sorry everyone had a super busy June and just back getting in here. Glad to see ya'll were able to work this out and get it merged!

**Pull request closed without merging**
